// <auto-generated />
using System;
using BTL_backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTL_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BTL_backend.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FarmerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiaThuMua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LaiSuat")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("MaHopDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MuaVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("SanPhamThuMua")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrangThai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId");

                    b.HasIndex("MaHopDong")
                        .IsUnique();

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FarmerId = 1,
                            GiaThuMua = 7500m,
                            LaiSuat = 0.5m,
                            MaHopDong = "HD-2025-001",
                            MuaVu = "Đông-Xuân 2025",
                            NgayBatDau = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SanPhamThuMua = "Lúa IR50404",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 2,
                            FarmerId = 3,
                            GiaThuMua = 8200m,
                            LaiSuat = 0m,
                            MaHopDong = "HD-2025-002",
                            MuaVu = "Đông-Xuân 2025",
                            NgayBatDau = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SanPhamThuMua = "Lúa Jasmine 85",
                            TrangThai = 0
                        },
                        new
                        {
                            Id = 3,
                            FarmerId = 4,
                            GiaThuMua = 7200m,
                            LaiSuat = 0.5m,
                            MaHopDong = "HD-2025-003",
                            MuaVu = "Hè-Thu 2025",
                            NgayBatDau = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayTao = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SanPhamThuMua = "Lúa IR50404",
                            TrangThai = 0
                        });
                });

            modelBuilder.Entity("BTL_backend.Models.Farmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DienTichCanhTac")
                        .HasColumnType("TEXT");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoCCCD")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Farmers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaChi = "Ấp 1, Xã An Phú",
                            DienTichCanhTac = 2.5m,
                            HoTen = "Nguyễn Văn An",
                            NgayTao = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoCCCD = "079201001234",
                            SoDienThoai = "0901234567",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 2,
                            DiaChi = "Ấp 3, Xã An Phú",
                            DienTichCanhTac = 1.8m,
                            HoTen = "Trần Thị Bé",
                            NgayTao = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoCCCD = "079201005678",
                            SoDienThoai = "0912345678",
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 3,
                            DiaChi = "Ấp 2, Xã Tân Thạnh",
                            DienTichCanhTac = 3.2m,
                            HoTen = "Lê Văn Cường",
                            NgayTao = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoCCCD = "080201002345",
                            SoDienThoai = "0923456789",
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 4,
                            DiaChi = "Ấp 5, Xã Mỹ Lộc",
                            DienTichCanhTac = 4.0m,
                            HoTen = "Phạm Thị Diệu",
                            NgayTao = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoCCCD = "082201003456",
                            SoDienThoai = "0934567890",
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 5,
                            DiaChi = "Ấp 1, Xã Long Hòa",
                            DienTichCanhTac = 2.0m,
                            HoTen = "Huỳnh Văn Em",
                            NgayTao = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoCCCD = "086201004567",
                            SoDienThoai = "0945678901",
                            ZoneId = 4
                        });
                });

            modelBuilder.Entity("BTL_backend.Models.Harvest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatLuong")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GiaThuMua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayThuMua")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenNongSan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Harvests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChatLuong = "Loại 1",
                            ContractId = 1,
                            GiaThuMua = 7500m,
                            NgayThuMua = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuong = 5000m,
                            TenNongSan = "Lúa IR50404",
                            ThanhTien = 37500000m
                        },
                        new
                        {
                            Id = 2,
                            ChatLuong = "Loại 1",
                            ContractId = 2,
                            GiaThuMua = 8200m,
                            NgayThuMua = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuong = 7000m,
                            TenNongSan = "Lúa Jasmine 85",
                            ThanhTien = 57400000m
                        });
                });

            modelBuilder.Entity("BTL_backend.Models.Settlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayQuyetToan")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoTienThucNhan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienLai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongNoVatTu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienThuMua")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.ToTable("Settlements");
                });

            modelBuilder.Entity("BTL_backend.Models.Supply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoaiVatTu")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenVatTu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Supplies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DonGia = 15000m,
                            DonViTinh = "kg",
                            LoaiVatTu = "Giống",
                            MoTa = "Giống lúa năng suất cao",
                            TenVatTu = "Giống lúa IR50404"
                        },
                        new
                        {
                            Id = 2,
                            DonGia = 22000m,
                            DonViTinh = "kg",
                            LoaiVatTu = "Giống",
                            MoTa = "Giống lúa thơm chất lượng",
                            TenVatTu = "Giống lúa Jasmine 85"
                        },
                        new
                        {
                            Id = 3,
                            DonGia = 850000m,
                            DonViTinh = "bao (50kg)",
                            LoaiVatTu = "Phân bón",
                            MoTa = "Phân bón tổng hợp",
                            TenVatTu = "Phân NPK 20-20-15"
                        },
                        new
                        {
                            Id = 4,
                            DonGia = 520000m,
                            DonViTinh = "bao (50kg)",
                            LoaiVatTu = "Phân bón",
                            MoTa = "Phân đạm",
                            TenVatTu = "Phân Ure Phú Mỹ"
                        },
                        new
                        {
                            Id = 5,
                            DonGia = 45000m,
                            DonViTinh = "gói",
                            LoaiVatTu = "Thuốc BVTV",
                            MoTa = "Thuốc trừ sâu đục thân",
                            TenVatTu = "Thuốc trừ sâu Regent 800WG"
                        });
                });

            modelBuilder.Entity("BTL_backend.Models.SupplyDebt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayLay")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupplyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("SupplyId");

                    b.ToTable("SupplyDebts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractId = 1,
                            DonGia = 15000m,
                            NgayLay = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuong = 50m,
                            SupplyId = 1,
                            ThanhTien = 750000m
                        },
                        new
                        {
                            Id = 2,
                            ContractId = 1,
                            DonGia = 850000m,
                            NgayLay = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuong = 10m,
                            SupplyId = 3,
                            ThanhTien = 8500000m
                        },
                        new
                        {
                            Id = 3,
                            ContractId = 1,
                            DonGia = 520000m,
                            NgayLay = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuong = 5m,
                            SupplyId = 4,
                            ThanhTien = 2600000m
                        },
                        new
                        {
                            Id = 4,
                            ContractId = 2,
                            DonGia = 22000m,
                            NgayLay = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuong = 80m,
                            SupplyId = 2,
                            ThanhTien = 1760000m
                        },
                        new
                        {
                            Id = 5,
                            ContractId = 2,
                            DonGia = 850000m,
                            NgayLay = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuong = 15m,
                            SupplyId = 3,
                            ThanhTien = 12750000m
                        });
                });

            modelBuilder.Entity("BTL_backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("VaiTro")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@agricontract.vn",
                            HoTen = "Quản trị viên",
                            HoatDong = true,
                            MatKhau = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            NgayTao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0900000000",
                            TenDangNhap = "admin",
                            VaiTro = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "hoa@agricontract.vn",
                            HoTen = "Nguyễn Thị Hoa",
                            HoatDong = true,
                            MatKhau = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            NgayTao = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0911111111",
                            TenDangNhap = "nhanvien1",
                            VaiTro = 1
                        });
                });

            modelBuilder.Entity("BTL_backend.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("HuyenQuan")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenThonXa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TinhThanhPho")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HuyenQuan = "Huyện Củ Chi",
                            TenThonXa = "Xã An Phú",
                            TinhThanhPho = "TP. Hồ Chí Minh"
                        },
                        new
                        {
                            Id = 2,
                            HuyenQuan = "Huyện Thủ Thừa",
                            TenThonXa = "Xã Tân Thạnh",
                            TinhThanhPho = "Long An"
                        },
                        new
                        {
                            Id = 3,
                            HuyenQuan = "Huyện Cao Lãnh",
                            TenThonXa = "Xã Mỹ Lộc",
                            TinhThanhPho = "Đồng Tháp"
                        },
                        new
                        {
                            Id = 4,
                            HuyenQuan = "Huyện Châu Thành",
                            TenThonXa = "Xã Long Hòa",
                            TinhThanhPho = "Tiền Giang"
                        },
                        new
                        {
                            Id = 5,
                            HuyenQuan = "Huyện Ô Môn",
                            TenThonXa = "Xã Phước Thới",
                            TinhThanhPho = "Cần Thơ"
                        });
                });

            modelBuilder.Entity("BTL_backend.Models.Contract", b =>
                {
                    b.HasOne("BTL_backend.Models.Farmer", "Farmer")
                        .WithMany("Contracts")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("BTL_backend.Models.Farmer", b =>
                {
                    b.HasOne("BTL_backend.Models.Zone", "Zone")
                        .WithMany("Farmers")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("BTL_backend.Models.Harvest", b =>
                {
                    b.HasOne("BTL_backend.Models.Contract", "Contract")
                        .WithMany("Harvests")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("BTL_backend.Models.Settlement", b =>
                {
                    b.HasOne("BTL_backend.Models.Contract", "Contract")
                        .WithOne("Settlement")
                        .HasForeignKey("BTL_backend.Models.Settlement", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("BTL_backend.Models.SupplyDebt", b =>
                {
                    b.HasOne("BTL_backend.Models.Contract", "Contract")
                        .WithMany("SupplyDebts")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTL_backend.Models.Supply", "Supply")
                        .WithMany("SupplyDebts")
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("BTL_backend.Models.Contract", b =>
                {
                    b.Navigation("Harvests");

                    b.Navigation("Settlement");

                    b.Navigation("SupplyDebts");
                });

            modelBuilder.Entity("BTL_backend.Models.Farmer", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("BTL_backend.Models.Supply", b =>
                {
                    b.Navigation("SupplyDebts");
                });

            modelBuilder.Entity("BTL_backend.Models.Zone", b =>
                {
                    b.Navigation("Farmers");
                });
#pragma warning restore 612, 618
        }
    }
}
